<a href="https://colab.research.google.com/github/ByungChul-Cha/Deep_Learning_Study/blob/main/Day03/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%9E%85%EB%AC%B8%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Manipulation
**(중요) [텐서 조작하기](https://wikidocs.net/52460)**
- 정확한 개념 확인하기

In [ ]:
pip install torch

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))


Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

# **03-01. Linear Regression & Autograd(선형 회귀와 자동 미분)**

# optimizer.zero_grad()가 필요한 이유
- pytorch는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있음
- zero_grad()를 통해 미분값을 계속 0으로 초기화

In [ ]:
import torch
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

  z = 2*w

  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


# torch.manual_seed()를 하는 이유
- manual_seed()를 사용한 프로그램의 결과는 다른 컴퓨터에서 실행시켜도 동일한 결과

# Autograd(자동 미분) 실습

In [ ]:
import torch

w = torch.tensor(2.0, requires_grad=True)

y = w**2
z = 2*y + 5

# 수식 z의 w에 대한 기울기 계산
z.backward()

print("수식을 w로 미분한 값 : {}".format(w.grad))

수식을 w로 미분한 값 : 8.0


# **03-02. Multivariable Linear Regression(다중 선형 회귀)**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
# 훈련 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
# 가중치 w와 편향 b 초기화
# 학습 데이터가 3개이므로 가중치도 3개 선언
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))


Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


# 벡터와 행렬 연산으로 바꾸기
- 위의 방식은 특징의 개수가 많아지면 하나씩 선언해야 되는 문제 발생

In [ ]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  80],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if (epoch%100==0):
      print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
      ))

Epoch    0/1000 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch  100/1000 hypothesis: tensor([154.0433, 185.0925, 175.8312, 198.5701, 141.2221]) Cost: 5.754568
Epoch  200/1000 hypothesis: tensor([154.0278, 185.0649, 175.9335, 198.5128, 141.2284]) Cost: 5.512375
Epoch  300/1000 hypothesis: tensor([154.0120, 185.0385, 176.0329, 198.4569, 141.2353]) Cost: 5.281663
Epoch  400/1000 hypothesis: tensor([153.9960, 185.0133, 176.1295, 198.4022, 141.2426]) Cost: 5.061868
Epoch  500/1000 hypothesis: tensor([153.9797, 184.9892, 176.2233, 198.3488, 141.2504]) Cost: 4.852397
Epoch  600/1000 hypothesis: tensor([153.9632, 184.9662, 176.3143, 198.2966, 141.2586]) Cost: 4.652731
Epoch  700/1000 hypothesis: tensor([153.9465, 184.9442, 176.4028, 198.2456, 141.2672]) Cost: 4.462276
Epoch  800/1000 hypothesis: tensor([153.9296, 184.9232, 176.4888, 198.1958, 141.2762]) Cost: 4.280613
Epoch  900/1000 hypothesis: tensor([153.9126, 184.9032, 176.5724, 198.1471, 141.2855]) Cost: 4.107294
Epoch 

In [ ]:
# 임의의 입력 값에 대한 예측
with torch.no_grad():
    new_input = torch.FloatTensor([[75, 85, 72]])  # 예측하고 싶은 임의의 입력
    prediction = new_input.matmul(W) + b
    print('Predicted value for input {}: {}'.format(new_input.squeeze().tolist(), prediction.item()))

Predicted value for input [75.0, 85.0, 72.0]: 157.25311279296875


- torch.no_grad(): 수행되는 모든 연산에 대해 역전파를 비활성화
- new_input: 예측하고자 하는 새로운 입력 값 정의
- prediction: 모델이 예측을 수행
- new_input.squeeze().tolist(): 입력 값을 리스트 형태로 변환
- prediction.item(): 모델이 예측한 값을 파이썬 숫자 자료형으로 변환해 출력

# **03-03. nn.Module과 클래스로 구현하기**

# 단순 선형 회귀 구현하기
- nn.Linear(): 선형 회귀 모델
- nn.functional.mse_loss(): 평균 제곱오차

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3],[5]])
y_train = torch.FloatTensor([[2], [4], [6],[10]])

# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)

# model에 저장되어있는 가중치 W와 편향 b 출력
# 첫번째 값이 W, 두번째 값이 b
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.2057]], requires_grad=True), Parameter containing:
tensor([0.5087], requires_grad=True)]


In [ ]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=1e-2)

In [ ]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 41.522934
Epoch  100/2000 Cost: 0.109222
Epoch  200/2000 Cost: 0.047545
Epoch  300/2000 Cost: 0.020697
Epoch  400/2000 Cost: 0.009009
Epoch  500/2000 Cost: 0.003922
Epoch  600/2000 Cost: 0.001707
Epoch  700/2000 Cost: 0.000743
Epoch  800/2000 Cost: 0.000324
Epoch  900/2000 Cost: 0.000141
Epoch 1000/2000 Cost: 0.000061
Epoch 1100/2000 Cost: 0.000027
Epoch 1200/2000 Cost: 0.000012
Epoch 1300/2000 Cost: 0.000005
Epoch 1400/2000 Cost: 0.000002
Epoch 1500/2000 Cost: 0.000001
Epoch 1600/2000 Cost: 0.000000
Epoch 1700/2000 Cost: 0.000000
Epoch 1800/2000 Cost: 0.000000
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [ ]:
# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[8.0000]], grad_fn=<AddmmBackward0>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9999]], requires_grad=True), Parameter containing:
tensor([0.0003], requires_grad=True)]


- forward 연산: H(x) 식에 입력으로부터 예측된 값을 얻는 것
  - 학습 전, prediction=model(x_train)
  - 학습 후, pred_y=model(new_var)
- backward 연산: 학습 과정에서 비용 함수를 미분하여 기울기를 구하는 것
  - cost.backward()

# 다중 선형 회귀 구현하기

In [ ]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

print(list(model.parameters()))

[Parameter containing:
tensor([[-0.3236, -0.0950, -0.0112]], requires_grad=True), Parameter containing:
tensor([0.0843], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 43611.324219
Epoch  100/2000 Cost: 2.979667
Epoch  200/2000 Cost: 2.848366
Epoch  300/2000 Cost: 2.723935
Epoch  400/2000 Cost: 2.605963
Epoch  500/2000 Cost: 2.494148
Epoch  600/2000 Cost: 2.388146
Epoch  700/2000 Cost: 2.287657
Epoch  800/2000 Cost: 2.192376
Epoch  900/2000 Cost: 2.102051
Epoch 1000/2000 Cost: 2.016406
Epoch 1100/2000 Cost: 1.935199
Epoch 1200/2000 Cost: 1.858181
Epoch 1300/2000 Cost: 1.785156
Epoch 1400/2000 Cost: 1.715922
Epoch 1500/2000 Cost: 1.650246
Epoch 1600/2000 Cost: 1.587948
Epoch 1700/2000 Cost: 1.528871
Epoch 1800/2000 Cost: 1.472824
Epoch 1900/2000 Cost: 1.419649
Epoch 2000/2000 Cost: 1.369225


In [ ]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.3660]], grad_fn=<AddmmBackward0>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.6127, 0.5794, 0.8159]], requires_grad=True), Parameter containing:
tensor([0.0976], requires_grad=True)]


# 모델을 클래스로 구현하기

In [ ]:
# 선형 회귀 모델
# 원래 코드
model = nn.Linear(1,1)

# 클래스로 구현한 코드
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)

  def forward(self, x):
    return self.linear(x)

model = LinearRegressionModel()

# 다중 선형 회귀 모델
# 원래 코드
model_multi = nn.Linear(3,1)

# 클래스로 구현한 코드
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)

  def forward(self, x):
    return self.linear(x)

model_multi = MultivariateLinearRegressionModel()

In [ ]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 최적화 모델
optimizer = torch.optim.SGD(model.parameters(), lr=1e-2)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
  # H(x) 계산
  prediction = model(x_train)

  # cost 계산
  cost = F.mse_loss(prediction, y_train)

  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

print(list(model.parameters()))

Epoch    0/2000 Cost: 38.548855
Epoch  100/2000 Cost: 0.030482
Epoch  200/2000 Cost: 0.018836
Epoch  300/2000 Cost: 0.011640
Epoch  400/2000 Cost: 0.007193
Epoch  500/2000 Cost: 0.004445
Epoch  600/2000 Cost: 0.002746
Epoch  700/2000 Cost: 0.001697
Epoch  800/2000 Cost: 0.001049
Epoch  900/2000 Cost: 0.000648
Epoch 1000/2000 Cost: 0.000400
Epoch 1100/2000 Cost: 0.000247
Epoch 1200/2000 Cost: 0.000153
Epoch 1300/2000 Cost: 0.000094
Epoch 1400/2000 Cost: 0.000058
Epoch 1500/2000 Cost: 0.000036
Epoch 1600/2000 Cost: 0.000022
Epoch 1700/2000 Cost: 0.000014
Epoch 1800/2000 Cost: 0.000009
Epoch 1900/2000 Cost: 0.000005
Epoch 2000/2000 Cost: 0.000003
[Parameter containing:
tensor([[1.9979]], requires_grad=True), Parameter containing:
tensor([0.0047], requires_grad=True)]


# **03-04. Mini Batch and DataLoader(미니 배치와 데이터 로더)**

# Mini Batch and Batch Size
- Mini Batch: 전체 데이터를 더 작은 단위로 나눠서 해당 단위로 학습
- Epoch: 전체 훈련 데이터가 학습에 한 번 사용된 주기
- Batch Gradient Descent
  - 정의: 전체 데이터에 대해서 한 번에 경사 하강법을 수행하는 방법
  - 장점: 최적값에 수렴하는 과정이 매우 안정
  - 단점: 계산량이 너무 큼
- Minibatch Gradient Descent
  - 정의: 미니 배치 단위로 경사 하강법을 수행하는 방법
  - 장점: 훈련 속도가 빠름
  - 단점: 최적값에 수렴하는 과정이 불안정


# Iteration
- 정의: 한번의 에포크 내에서 이루어지는 매개변수의 업데이트 횟수
  - ex) 전체 데이터가 2,000일 때 배치 크기가 200이라면 이터레이션의 수는 10

# Data Load
- Dataset을 정의 -> DataLoader에 전달

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
from torch.utils.data import TensorDataset, DataLoader

In [ ]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  90],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

dataset = TensorDataset(x_train, y_train)

In [ ]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [ ]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs+1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 1.108508
Epoch    0/20 Batch 2/3 Cost: 9.568531
Epoch    0/20 Batch 3/3 Cost: 10.699415
Epoch    1/20 Batch 1/3 Cost: 5.105576
Epoch    1/20 Batch 2/3 Cost: 4.790657
Epoch    1/20 Batch 3/3 Cost: 12.780603
Epoch    2/20 Batch 1/3 Cost: 9.408722
Epoch    2/20 Batch 2/3 Cost: 5.787118
Epoch    2/20 Batch 3/3 Cost: 0.904118
Epoch    3/20 Batch 1/3 Cost: 3.834690
Epoch    3/20 Batch 2/3 Cost: 16.551128
Epoch    3/20 Batch 3/3 Cost: 2.096963
Epoch    4/20 Batch 1/3 Cost: 6.599385
Epoch    4/20 Batch 2/3 Cost: 4.069488
Epoch    4/20 Batch 3/3 Cost: 10.579665
Epoch    5/20 Batch 1/3 Cost: 13.918554
Epoch    5/20 Batch 2/3 Cost: 8.924627
Epoch    5/20 Batch 3/3 Cost: 0.078399
Epoch    6/20 Batch 1/3 Cost: 5.953535
Epoch    6/20 Batch 2/3 Cost: 9.064077
Epoch    6/20 Batch 3/3 Cost: 2.997216
Epoch    7/20 Batch 1/3 Cost: 0.397693
Epoch    7/20 Batch 2/3 Cost: 9.714972
Epoch    7/20 Batch 3/3 Cost: 11.616889
Epoch    8/20 Batch 1/3 Cost: 8.332286
Epoch    8/20 Batch

In [ ]:
new_var = torch.FloatTensor([73, 80, 75])
pred_y = model(new_var)
print("훈련 후 입력 73, 80, 75일 때의 예측 값 : ", pred_y)

훈련 후 입력 73, 80, 75일 때의 예측 값 :  tensor([154.4937], grad_fn=<ViewBackward0>)


# Custom Dataset(커스텀 데이터 셋)
- torch.utils.data.Dataset을 상속받아 직접 커스텀 데이터셋을 만드는 경우도 있음
- 필요한 기본적인 define은 3개
  - __inti__, __len__, __getitem__

In [ ]:
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

In [ ]:
# Dataset 상속
class CustomDataset(Dataset):
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]
  def __len__(self):
    return len(self.x_data)
  def __getitem__(self, idx):
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [ ]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))


Epoch    0/20 Batch 1/3 Cost: 25892.785156
Epoch    0/20 Batch 2/3 Cost: 3996.022705
Epoch    0/20 Batch 3/3 Cost: 1485.888062
Epoch    1/20 Batch 1/3 Cost: 700.028198
Epoch    1/20 Batch 2/3 Cost: 189.909149
Epoch    1/20 Batch 3/3 Cost: 101.789856
Epoch    2/20 Batch 1/3 Cost: 24.114342
Epoch    2/20 Batch 2/3 Cost: 2.278820
Epoch    2/20 Batch 3/3 Cost: 1.686598
Epoch    3/20 Batch 1/3 Cost: 0.118586
Epoch    3/20 Batch 2/3 Cost: 2.794595
Epoch    3/20 Batch 3/3 Cost: 0.000925
Epoch    4/20 Batch 1/3 Cost: 0.036759
Epoch    4/20 Batch 2/3 Cost: 0.059442
Epoch    4/20 Batch 3/3 Cost: 4.217666
Epoch    5/20 Batch 1/3 Cost: 0.671645
Epoch    5/20 Batch 2/3 Cost: 0.312562
Epoch    5/20 Batch 3/3 Cost: 3.579600
Epoch    6/20 Batch 1/3 Cost: 0.717105
Epoch    6/20 Batch 2/3 Cost: 1.430445
Epoch    6/20 Batch 3/3 Cost: 0.903973
Epoch    7/20 Batch 1/3 Cost: 0.110341
Epoch    7/20 Batch 2/3 Cost: 0.032204
Epoch    7/20 Batch 3/3 Cost: 4.028187
Epoch    8/20 Batch 1/3 Cost: 0.927451
Epoch   